name: fcm_token_manager
description: An iOS/Android package to manage lifecycle of Firebase tokens.
repository: https://github.com/merkator95/fcm_token_manager
version: 0.1.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
