name: fcm_token_manager
description: An iOS/Android package to manage lifecycle of Firebase tokens.
repository: https://github.com/merkator95/fcm_token_manager
version: 0.1.4

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ">=5.1.0 <7.0.0"
