name: fcm_token_manager
description: An iOS/Android package to manage lifecycle of Firebase tokens.
repository: https://github.com/merkator95/fcm_token_manager
version: 0.1.6

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0
